name: harshit-frontend-ci-pipeline
trigger:
- none
stages:
- stage:
  jobs:
  - job:
    pool: 
      harshitpool
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'harshitdockerhub'
        repository: 'harshit281/frontendproject_1'
        command: 'buildAndPush'
        dockerfile: 'Dockerfile'
        tags: 'frontend-image-itc'
