name: harshit-login-ci-pipeline
trigger:
- none
stages:
- stage:
  jobs:
  - job:
    pool: 
      harshitpool
    steps:
    - task: Maven@4
      displayName: 'Build-jar-File-login'
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: 'install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        sonarQubeRunAnalysis: false
    - task: Docker@2
      inputs:
        containerRegistry: 'harshitdockerhub'
        repository: 'harshit281/frontendproject_1'
        command: 'buildAndPush'
        dockerfile: 'Dockerfile'
        tags: 'login-image-itc'
